
[project]
name = "mock-ApiRest-Flask"
version = "0.1.0"
description = "Mock API REST with Flask"
authors = [
    {name = "Eduardo da Silva", email = "eduardo.silva@gmail.com"},
]
dependencies = [
    "Flask>=2.3.2",
]
requires-python = ">=3.10"
license = {text = "MIT"}
